create table if not exists public.users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password_hash text not null,
  full_name text,
  email text,
  status text not null default 'Active',
  subscription_expiry text,
  created_at timestamptz not null default now(),
  role text not null default 'customer'
);

create index if not exists users_username_idx on public.users(username);
create index if not exists users_email_idx on public.users(email);

alter table public.users enable row level security;

drop policy if exists "server role full access" on public.users;
create policy "server role full access"
  on public.users
  for all
  to service_role
  using (true)
  with check (true);